/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include "tcMenuU8g2.h"
#include <RuntimeMenuItem.h>
#include <EditableLargeNumberMenuItem.h>
#include <IoAbstraction.h>
#include <ArduinoEEPROMAbstraction.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern U8G2_SSD1306_128X64_NONAME_F_HW_I2C gfx;
extern GraphicsDeviceRenderer renderer;

// Any externals needed by IO expanders, EEPROMs etc


// Global Menu Item exports
extern AnalogMenuItem menuSettingsD;
extern AnalogMenuItem menuSettingsI;
extern AnalogMenuItem menuSettingsP;
extern ActionMenuItem menuSettingsPIDTune;
extern ActionMenuItem menuSettingsSaveSettings;
extern AnalogMenuItem menuSettingsMotorCurrent;
extern AnalogMenuItem menuSettingsMicrosteps;
extern AnalogMenuItem menuSettingsSpoolRadius;
extern AnalogMenuItem menuSettingsGearboxRatio;
extern AnalogMenuItem menuSettingsMotorSteps;
extern AnalogMenuItem menuSettingsSerialNumber2;
extern EditableLargeNumberMenuItem menuSettingsSerialNumber;
extern TextMenuItem menuSettingsUserName;
extern BackMenuItem menuBackSettings;
extern SubMenuItem menuSettings;
extern AnalogMenuItem menuFan;
extern AnalogMenuItem menuActualTemp;
extern AnalogMenuItem menuTemperature;
extern AnalogMenuItem menuFeed;
extern ActionMenuItem menuStart;

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return menuStart; }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION onNameChanged(int id);
void CALLBACK_FUNCTION onPIDTune(int id);
void CALLBACK_FUNCTION onSaveSettings(int id);
void CALLBACK_FUNCTION onStart(int id);

#endif // MENU_GENERATED_CODE_H
