name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run --environment btt_ebb42_v1_1

      - name: "Build & test"
        run: |
          echo "done!"
          
  # The release job only runs when you push a tag starting with "v", e.g. v1.0.0 
  release:
    name: Release
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Upload release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: .pio/build/btt_ebb42_v1_1/firmware.bin
          generateReleaseNotes: true
